spring:
  application:
    name: JWTAuth
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
    url: jdbc:h2:file:./data/database;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /database
server:
  port: 8051

app:
  jwtSecret: 2aA4s9ks2rHhyZ&JaDH^44voLZKx
  jwtExpirationMs: 80000